apiVersion: v1
name: oauth
version: 1.0.11
appVersion: v2.22.0
description: Dex
keywords:
- kubermatic
- oauth
- dex
home: https://github.com/dexidp/dex
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
