apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ template "name" . }}'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ template "name" . }}'
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.helmExporter.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ .Chart.Name }}'
      app.kubernetes.io/instance: '{{ template "name" . }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ .Chart.Name }}'
        app.kubernetes.io/instance: '{{ template "name" . }}'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9571'
        kubermatic.io/chart: helm-exporter
    spec:
      containers:
      - name: '{{ .Chart.Name }}'
        image: '{{ .Values.helmExporter.image.repository }}:{{ .Values.helmExporter.image.tag }}'
        imagePullPolicy: {{ .Values.helmExporter.image.pullPolicy }}
        args:
        - '-tiller-namespaces={{ .Values.helmExporter.tillerNamespace }}'
        ports:
        - name: http
          containerPort: 9571
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
{{ toYaml .Values.helmExporter.resources | indent 10 }}
      serviceAccountName: '{{ template "name" . }}'
      nodeSelector:
{{ toYaml .Values.helmExporter.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.helmExporter.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.helmExporter.tolerations | indent 8 }}
