apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager
  template:
    metadata:
      labels:
        app: cert-manager
      annotations:
        kubermatic/scrape: 'true'
        kubermatic/scrape_port: '9402'
        fluentbit.io/parser: glog
    spec:
      serviceAccountName: cert-manager
      containers:
      - name: cert-manager
        image: '{{ .Values.certManager.controller.image.repository }}:{{ .Values.certManager.controller.image.tag }}'
        imagePullPolicy: {{ .Values.certManager.controller.image.pullPolicy }}
        args:
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
        {{- with .Values.certManager.ingressShim }}
        {{- if .defaultIssuerName }}
        - --default-issuer-name={{ .defaultIssuerName }}
        {{- end }}
        {{- if .defaultIssuerKind }}
        - --default-issuer-kind={{ .defaultIssuerKind }}
        {{- end }}
        {{- if .defaultACMEChallengeType }}
        - --default-acme-issuer-challenge-type={{ .defaultACMEChallengeType }}
        {{- end }}
        {{- if .defaultACMEDNS01ChallengeProvider }}
        - --default-acme-issuer-dns01-provider-name={{ .defaultACMEDNS01ChallengeProvider }}
        {{- end }}
        {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.certManager.http_proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.certManager.http_proxy }}
        {{- end }}
        {{- if .Values.certManager.https_proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.certManager.https_proxy }}
        {{- end }}
        {{- if .Values.certManager.no_proxy }}
        - name: NO_PROXY
          value: {{ .Values.certManager.no_proxy }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 9402
        resources:
{{ toYaml .Values.certManager.controller.resources | indent 10 }}
      {{- if .Values.certManager.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.certManager.securityContext.fsGroup }}
        runAsUser: {{ .Values.certManager.securityContext.runAsUser }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.certManager.controller.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.certManager.controller.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.certManager.controller.tolerations | indent 8 }}
