# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

groups:
- name: blackbox-exporter
  rules:
  - alert: HttpProbeFailed
    annotations:
      message: Probing the blackbox-exporter target {{ $labels.instance }} failed.
      runbook_url: https://docs.kubermatic.com/kubermatic/master/monitoring/runbook/#alert-httpprobefailed
    expr: probe_success != 1
    for: 5m
    labels:
      severity: warning

  - alert: HttpProbeSlow
    annotations:
      message: '{{ $labels.instance }} takes {{ $value }} seconds to respond.'
      runbook_url: https://docs.kubermatic.com/kubermatic/master/monitoring/runbook/#alert-httpprobeslow
    expr: sum by (instance) (probe_http_duration_seconds) > 3
    for: 15m
    labels:
      severity: warning
    runbook:
      steps:
      - Check the target system's resource usage for anomalias.
      - Check if the target application has been recently rescheduled and is still settling.

  - alert: HttpCertExpiresSoon
    annotations:
      message: The certificate for {{ $labels.instance }} expires in less than 3 days.
      runbook_url: https://docs.kubermatic.com/kubermatic/master/monitoring/runbook/#alert-httpcertexpiressoon
    expr: probe_ssl_earliest_cert_expiry - time() < 3*24*3600
    labels:
      severity: warning

  - alert: HttpCertExpiresVerySoon
    annotations:
      message: The certificate for {{ $labels.instance }} expires in less than 24 hours.
      runbook_url: https://docs.kubermatic.com/kubermatic/master/monitoring/runbook/#alert-httpcertexpiresverysoon
    expr: probe_ssl_earliest_cert_expiry - time() < 24*3600
    labels:
      severity: critical
