# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

groups:
- name: elasticsearch
  rules:
  - alert: ElasticsearchHeapTooHigh
    annotations:
      message: The heap usage of Elasticsearch node {{ $labels.name }} is over 90%.
      runbook_url: https://docs.loodse.com/kubermatic/master/monitoring/runbook/#alert-elasticsearchheaptoohigh
    expr: elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"} > 0.9
    for: 15m
    labels:
      severity: warning
    runbook:
      steps:
      - Check the pod's logs for anomalities.
      - If it is a data node, check the shard allocation via `http://es-data:9200/_cat/shards?v`.

  - alert: ElasticsearchClusterUnavailable
    annotations:
      message: The Elasticsearch cluster health endpoint does not respond to scrapes.
      runbook_url: https://docs.loodse.com/kubermatic/master/monitoring/runbook/#alert-elasticsearchclusterunavailable
    expr: elasticsearch_cluster_health_up == 0
    for: 15m
    labels:
      severity: warning

  - alert: ElasticsearchClusterUnhealthy
    annotations:
      message: The Elasticsearch cluster is not healthy.
      runbook_url: https://docs.loodse.com/kubermatic/master/monitoring/runbook/#alert-elasticsearchclusterunhealthy
    expr: elasticsearch_cluster_health_status{color="green"} == 0
    for: 15m
    labels:
      severity: critical

  - alert: ElasticsearchUnassignedShards
    annotations:
      message: There are {{ $value }} unassigned shards in the Elasticsearch cluster.
      runbook_url: https://docs.loodse.com/kubermatic/master/monitoring/runbook/#alert-elasticsearchunassignedshards
    expr: elasticsearch_cluster_health_unassigned_shards > 0
    for: 15m
    labels:
      severity: critical
    runbook:
      steps:
      - Check the shard allocation via `http://es-data:9200/_cat/shards?v`.
