# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

groups:
- name: helm-exporter
  rules:
  - alert: HelmReleaseNotDeployed
    annotations:
      message:
        The Helm release `{{ $labels.release }}` (`{{ $labels.chart }}` chart in namespace `{{ $labels.exported_namespace }}`)
        in version {{ $labels.version }} has not been ready for more than 15 minutes.
      runbook_url: https://docs.kubermatic.com/kubermatic/master/monitoring/runbook/#alert-helmreleasenotdeployed
    expr: helm_chart_info != 1
    for: 15m
    labels:
      severity: warning
    runbook:
      steps:
      - Check the installed Helm releases via `helm --tiller-namespace kubermtic-installer ls`.
      - If all releases are status `DEPLOYED`, make sure the helme-exporter is looking at the correct Tiller by checking
        the `values.yaml` flag `helmExporter.tillerNamespace`.
      - If Helm cannot repair the chart automatically, delete/purge the chart (`helm delete --purge [RELEASE]`) and
        re-install the chart again. Re-installing charts will not affect any existing data in existing PersistentVolumeClaims.
