# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

groups:
  - name: node-exporter
    rules:
      - record: node:node_num_cpu:sum
        expr: |
          count by (node) (sum by (node, cpu) (
            node_cpu_seconds_total{app="node-exporter"}
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          ))

      - record: :node_cpu_utilisation:avg1m
        expr: |
          1 - avg(rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m]))

      - record: node:node_cpu_utilisation:avg1m
        expr: |
          1 - avg by (node) (
            rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m])
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:)

      - record: ":node_cpu_saturation_load1:"
        expr: |
          sum(node_load1{app="node-exporter"})
          /
          sum(node:node_num_cpu:sum)

      - record: "node:node_cpu_saturation_load1:"
        expr: |
          sum by (node) (
            node_load1{app="node-exporter"}
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )
          /
          node:node_num_cpu:sum

      - record: node:cluster_cpu_utilisation:ratio
        expr: |
          node:node_cpu_utilisation:avg1m
            *
          node:node_num_cpu:sum
            /
          scalar(sum(node:node_num_cpu:sum))

      - record: ":node_memory_utilisation:"
        expr: |
          1 -
          sum(node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
          /
          sum(node_memory_MemTotal_bytes{app="node-exporter"})

      - record: node:node_memory_bytes_available:sum
        expr: |
          sum by (node) (
            (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
          )

      - record: node:node_memory_bytes_total:sum
        expr: |
          sum by (node) (
            node_memory_MemTotal_bytes{app="node-exporter"}
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
          )

      - record: node:node_memory_utilisation:ratio
        expr: |
          (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
          /
          scalar(sum(node:node_memory_bytes_total:sum))

      - record: :node_memory_swap_io_bytes:sum_rate
        expr: |
          1e3 * sum(
            (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
            + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
          )

      - record: "node:node_memory_utilisation:"
        expr: |
          1 -
          sum by (node) (
            (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )
          /
          sum by (node) (
            node_memory_MemTotal_bytes{app="node-exporter"}
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )

      - record: "node:node_memory_utilisation_2:"
        expr: |
          1 - (node:node_memory_bytes_available:sum / node:node_memory_bytes_total:sum)

      - record: node:node_memory_swap_io_bytes:sum_rate
        expr: |
          1e3 * sum by (node) (
            (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
            + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
            * on (namespace, pod) group_left(node)
              node_namespace_pod:kube_pod_info:
          )

      - record: node:cluster_memory_utilisation:ratio
        expr: |
          (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
          /
          scalar(sum(node:node_memory_bytes_total:sum))

      - record: :node_disk_utilisation:avg_irate
        expr: |
          avg(irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+"}[1m]))

      - record: node:node_disk_utilisation:avg_irate
        expr: |
          avg by (node) (
            irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+"}[1m])
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )

      - record: :node_disk_saturation:avg_irate
        expr: |
          avg(irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+"}[1m]) / 1e3)

      - record: node:node_disk_saturation:avg_irate
        expr: |
          avg by (node) (
            irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+"}[1m]) / 1e3
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )

      - record: "node:node_filesystem_usage:"
        expr: |
          max by (namespace, pod, device) ((node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
          - node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
          / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})

      - record: "node:node_filesystem_avail:"
        expr: |
          max by (namespace, pod, device) (node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})

      - record: :node_net_utilisation:sum_irate
        expr: |
          sum(irate(node_network_receive_bytes_total{app="node-exporter",device!~"veth.+"}[1m])) +
          sum(irate(node_network_transmit_bytes_total{app="node-exporter",device!~"veth.+"}[1m]))

      - record: node:node_net_utilisation:sum_irate
        expr: |
          sum by (node) (
            (irate(node_network_receive_bytes_total{app="node-exporter",device!~"veth.+"}[1m]) +
            irate(node_network_transmit_bytes_total{app="node-exporter",device!~"veth.+"}[1m]))
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )

      - record: :node_net_saturation:sum_irate
        expr: |
          sum(irate(node_network_receive_drop_total{app="node-exporter",device!~"veth.+"}[1m])) +
          sum(irate(node_network_transmit_drop_total{app="node-exporter",device!~"veth.+"}[1m]))

      - record: node:node_net_saturation:sum_irate
        expr: |
          sum by (node) (
            (irate(node_network_receive_drop_total{app="node-exporter",device!~"veth.+"}[1m]) +
            irate(node_network_transmit_drop_total{app="node-exporter",device!~"veth.+"}[1m]))
          * on (namespace, pod) group_left(node)
            node_namespace_pod:kube_pod_info:
          )

      ############################################################
      # alerts
      ############################################################

      - alert: NodeFilesystemSpaceFillingUp
        annotations:
          message:
            Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
            to run out of space within the next 24 hours.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemspacefillingup
        expr: |
          predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 24*60*60) < 0
          and
          node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.4
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: warning
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemSpaceFillingUp
        annotations:
          message:
            Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
            to run out of space within the next 4 hours.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemspacefillingup
        expr: |
          predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) < 0
          and
          node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.2
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemOutOfSpace
        annotations:
          message:
            Filesystem on node {{ $labels.node_name }} having IP {{ $labels.instance }} has only
            {{ $value }}% available space left on drive {{ $labels.device }}.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemoutofspace
        expr: |
          node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 10
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 30m
        labels:
          severity: warning
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemOutOfSpace
        annotations:
          message:
            Filesystem on node {{ $labels.node_name }} having IP {{ $labels.instance }} has only
            {{ $value }}% available space left on drive {{ $labels.device }}.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemoutofspace
        expr: |
          node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 5
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 10m
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemFilesOutOfSpace
        annotations:
          message: Filesystem on node {{ $labels.node_name }} having IP {{ $labels.instance }} has only {{ $value }}% inodes available on drive {{ $labels.device }}.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemfilesoutofspace
        expr: |
          node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 10
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemFilesFillingUp
        annotations:
          message:
            Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
            to run out of files within the next 24 hours.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemfilesfillingup
        expr: |
          predict_linear(node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"}[6h], 24*60*60) < 0
          and
          node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} < 0.4
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: warning
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemFilesFillingUp
        annotations:
          message:
            Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
            to run out of files within the next 4 hours.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemfilesfillingup
        expr: |
          predict_linear(node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) < 0
          and
          node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} < 0.2
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeFilesystemOutOfFiles
        annotations:
          message:
            Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only
            {{ $value }}% available inodes left.
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodefilesystemoutoffiles
        expr: |
          node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 5
          and
          node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
        for: 1h
        labels:
          severity: warning
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeNetworkReceiveErrs
        annotations:
          message:
            "{{ $labels.instance }} interface {{ $labels.device }} shows errors
            while receiving packets ({{ $value }} errors in two minutes)."
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodenetworkreceiveerrs
        expr: increase(node_network_receive_errs_total[2m]) > 10
        for: 1h
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeNetworkTransmitErrs
        annotations:
          message:
            "{{ $labels.instance }} interface {{ $labels.device }} shows errors
            while transmitting packets ({{ $value }} errors in two minutes)."
          runbook_url: https://docs.kubermatic.com/kubermatic/latest/cheat-sheets/alerting-runbook/#alert-nodenetworktransmiterrs
        expr: increase(node_network_transmit_errs_total[2m]) > 10
        for: 1h
        labels:
          severity: critical
          resource: "{{ $labels.instance }} {{ $labels.device }}"
          service: "node-exporter"

      - alert: NodeTimeDrift
        annotations:
          message: Time on Node {{ $labels.node_name }} drifts by a {{ $value }} seconds.
        expr: abs(timestamp(node_time_seconds) - node_time_seconds) > 1
        for: 15m
        labels:
          severity: critical
          resource: "{{ $labels.node_name }}"
          service: "node-exporter"

      - alert: HighClusterCPUUsage
        annotations:
          message: The average CPU usage across all nodes is above 80% for more than 5 minutes.
        expr: avg (100 - (rate(node_cpu_seconds_total{app_kubernetes_io_name="node-exporter", mode="idle"}[5m]) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: "node-exporter"

      - alert: HighClusterMemoryUsage
        annotations:
          message: The average memory usage across all nodes is above 80% for more than 5 minutes.
        expr: |
          max(
            (
              sum(
                node_memory_MemTotal_bytes{app_kubernetes_io_name="node-exporter", node_name=~".*"}
              - node_memory_MemFree_bytes{app_kubernetes_io_name="node-exporter", node_name=~".*"}
              - node_memory_Buffers_bytes{app_kubernetes_io_name="node-exporter", node_name=~".*"}
              - node_memory_Cached_bytes{app_kubernetes_io_name="node-exporter", node_name=~".*"}
              )
              /
              sum(
                node_memory_MemTotal_bytes{app_kubernetes_io_name="node-exporter", node_name=~".*"}
              )
            ) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: "node-exporter"

      - alert: HighNodeCPUUsage
        annotations:
          message: Node {{ $labels.node_name }} has CPU usage above 80% for more than 5 minutes.
        expr: avg by (node_name) (100 - (rate(node_cpu_seconds_total{app_kubernetes_io_name="node-exporter", mode="idle"}[5m]) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: "node-exporter"

      - alert: HighNodeMemoryUsage
        annotations:
          message: Node {{ $labels.node_name }} has memory usage above 80% for more than 5 minutes.
        expr: |
          avg by (node_name) (
            (
              node_memory_MemTotal_bytes{app_kubernetes_io_name="node-exporter"}
            - node_memory_MemFree_bytes{app_kubernetes_io_name="node-exporter"}
            - node_memory_Buffers_bytes{app_kubernetes_io_name="node-exporter"}
            - node_memory_Cached_bytes{app_kubernetes_io_name="node-exporter"}
            )
            /
            node_memory_MemTotal_bytes{app_kubernetes_io_name="node-exporter"}
          ) * 100
        for: 5m
        labels:
          severity: warning
          service: "node-exporter"
