apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubermatic-operator
  namespace: kubermatic-operator
  labels:
    app.kubernetes.io/name: kubermatic-operator
    app.kubernetes.io/version: '__KUBERMATIC_TAG__'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubermatic-operator
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/scrape_port: '8085'
        fluentbit.io/parser: json_iso
    spec:
      serviceAccountName: kubermatic-operator
      containers:
      - name: operator
        image: 'quay.io/kubermatic/api:__KUBERMATIC_TAG__'
        imagePullPolicy: IfNotPresent
        command:
        - kubermatic-operator
        args:
        - -internal-address=0.0.0.0:8085
        - -namespace=$(POD_NAMESPACE)
        - -log-format=json
        - -worker-name=kubermatic-operator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: 8085
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
