apiVersion: v1
name: blackbox-exporter
version: 1.0.3
appVersion: v0.16.0
description: Deploys the Prometheus Blackbox Exporter
keywords:
- kubermatic
- monitoring
- prometheus
- blackbox-exporter
home: https://github.com/prometheus/blackbox_exporter
sources:
- https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
