blackboxExporter:
  image:
    repository: docker.io/prom/blackbox-exporter
    tag: v0.14.0
    pullPolicy: IfNotPresent

  containers:
    blackboxExporter:
      resources:
        requests:
          cpu: 100m
          memory: 24Mi
        limits:
          cpu: 250m
          memory: 32Mi

  nodeSelector: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: blackbox-exporter
          topologyKey: kubernetes.io/hostname
        weight: 100
  tolerations: []

  modules:
    # A module that requires HTTPS and HTTP 2xx codes on its targets.
    https_2xx:
      prober: http
      timeout: 5s
      http:
        method: GET
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        fail_if_not_ssl: true
        preferred_ip_protocol: "ip4"
