groups:
- name: kube-apiserver
  rules:
  - alert: KubernetesApiserverDown
    expr: absent(up{job="apiserver"} == 1)
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: Kubernetes API Server unreachable
      description: Prometheus fails to scrape API Server(s), or all API servers have disappeared from service discovery.
  - alert: KubernetesApiServerLatency
    expr: histogram_quantile(0.99, sum(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"}) WITHOUT (instance, resource)) / 1e+06 > 1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: Kubernetes API Server latency is high
      description: 99th percentile Latency for {{ $labels.verb }} requests to the kube-apiserver is higher than 1s.
