groups:
- name: kube-state-metrics
  rules:
  - alert: KubernetesDeploymentGenerationMismatch
    expr: kube_deployment_status_observed_generation != kube_deployment_metadata_generation
    for: 15m
    labels:
      severity: warning
    annotations:
      description: "Observed deployment generation does not match expected one for deployment {{$labels.namespace}}/{{$labels.deployment}}"
      summary: "Deployment is outdated"
  - alert: KubernetesDeploymentReplicasNotUpdated
    expr: ((kube_deployment_status_replicas_updated != kube_deployment_spec_replicas) or (kube_deployment_status_replicas_available != kube_deployment_spec_replicas)) unless (kube_deployment_spec_paused == 1)
    for: 15m
    labels:
      severity: warning
    annotations:
      description: "Replicas are not updated and available for deployment {{$labels.namespace}}/{{$labels.deployment}}"
      summary: "Deployment replicas are outdated"
  - alert: KubernetesDaemonSetRolloutStuck
    expr: kube_daemonset_status_number_ready / kube_daemonset_status_desired_number_scheduled * 100 < 100
    for: 15m
    labels:
      severity: warning
    annotations:
      description: "Only {{$value}}% of desired pods scheduled and ready for daemon set {{$labels.namespace}}/{{$labels.daemonset}}"
      summary: "DaemonSet is missing pods"
  - alert: KubernetesDaemonSetsNotScheduled
    expr: kube_daemonset_status_desired_number_scheduled - kube_daemonset_status_current_number_scheduled > 0
    for: 10m
    labels:
      severity: warning
    annotations:
      description: "A number of daemonsets are not scheduled."
      summary: "Daemonsets are not scheduled correctly"
  - alert: KubernetesDaemonSetsMissScheduled
    expr: kube_daemonset_status_number_misscheduled > 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Daemonsets are not scheduled correctly"
      description: "A number of daemonsets are running where they are not supposed to run."
  - alert: KubernetesPodFrequentlyRestarting
    expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
    for: 10m
    labels:
      severity: warning
    annotations:
      description: "Pod {{$labels.namespace}}/{{$labels.pod}} is was restarted {{$value}} times within the last hour."
      summary: "Pod is restarting frequently"
  - alert: KubernetesPodTerminating
    expr: kube_pod_container_status_terminated{namespace!="kubermatic-installer"} == 1
    for: 30m
    labels:
      severity: warning
    annotations:
      description: "Container {{$labels.namespace}}/{{$labels.pod}}/{{$labels.container}} is terminating too long."
      summary: "Pod is terminating too long"
  - alert: KubernetesPodWaiting
    expr: kube_pod_container_status_waiting{namespace!="kubermatic-installer"} == 1
    for: 30m
    labels:
      severity: warning
    annotations:
      description: "Container {{$labels.namespace}}/{{$labels.pod}}/{{$labels.container}} is waiting too long."
      summary: "Pod is waiting too long"
