groups:
- name: machine-controller
  rules:
  - alert: MachineControllerDown
    expr: absent(up{job="machine-controller"} == 1) and (kubermatic_cluster_controller_cluster_status_phase{phase="running"} > 0)
    for: 5m
    labels:
      severity: critical
    annotations:
      description: "Machine Controller for cluster {{ $labels.cluster }} is down for more than 5 minutes."
      summary: "Machine Controller is down"
  - alert: MachineControllerTooManyErrors
    expr: sum(rate(machine_controller_errors_total[5m])) by (namespace) > 0.01
    for: 10m
    labels:
      severity: warning
    annotations:
      description: "Machine Controller in {{ $labels.namespace }} has too many errors in its loop."
      summary: "Machine Controller has many errors"
