groups:
- name: node-alerting.rules
  rules:
  - alert: DiskWillFillIn4Hours
    expr: predict_linear(node_filesystem_free{name="node-exporter"}[1h], 4 * 3600) < 0
    for: 5m
    labels:
      severity: page
  - alert: DiskWillFillIn8Hours
    expr: predict_linear(node_filesystem_free{name="node-exporter"}[1h], 8 * 3600) < 0
    for: 5m
    labels:
      severity: notify
