apiVersion: v1
name: kibana
version: 1.0.3
appVersion: 6.7.1
description: kibana
keywords:
- kubermatic
- logging
- kibana
- elastic
home: https://www.elastic.co/products/kibana
sources:
- https://github.com/helm/charts/tree/master/stable/kibana
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
