apiVersion: v1
name: kibana
version: 1.0.10
appVersion: 6.8.5
description: "[DEPRECATED] Kibana is a User Interface for Elasticsearch"
keywords:
- kubermatic
- logging
- kibana
- elastic
home: https://www.elastic.co/products/kibana
sources:
- https://github.com/helm/charts/tree/master/stable/kibana
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
