logging:
  kibana:
    image:
      repository: docker.elastic.co/kibana/kibana-oss
      tag: "6.7.1"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 450Mi
      limits:
        # need more cpu upon initialization, therefore burstable class
        cpu: 1000m
        memory: 600Mi

    setupContainer:
      image:
        repository: quay.io/kubermatic/util
        tag: 1.3.2
        pullPolicy: IfNotPresent
      resources:
        requests:
          cpu: 10m
          memory: 24Mi
        limits:
          cpu: 10m
          memory: 32Mi

    nodeSelector: {}
    affinity: {}
    tolerations: []
