logging:
  kibana:
    image:
      repository: docker.elastic.co/kibana/kibana
      tag: "6.5.1"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 400Mi
      limits:
        # need more cpu upon initialization, therefore burstable class
        cpu: 1000m
