kubermatic:
  docker:
    # the base64 encoded docker authentication token
    secret: ""
  # base64 encoded kubeconfig
  kubeconfig: ""
  rbac:
    replicas: 1
    image:
      repository: "kubermatic/api"
      tag: "v2.7.7"
      pullPolicy: "IfNotPresent"
