groups:
- name: node-exporter
  rules:
  - record: node:node_num_cpu:sum
    expr: |
      count by (node) (sum by (node, cpu) (
        node_cpu_seconds_total{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      ))

  - record: :node_cpu_utilisation:avg1m
    expr: |
      1 - avg(rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m]))

  - record: node:node_cpu_utilisation:avg1m
    expr: |
      1 - avg by (node) (
        rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:)

  - record: ':node_cpu_saturation_load1:'
    expr: |
      sum(node_load1{app="node-exporter"})
      /
      sum(node:node_num_cpu:sum)

  - record: 'node:node_cpu_saturation_load1:'
    expr: |
      sum by (node) (
        node_load1{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
      /
      node:node_num_cpu:sum

  - record: ':node_memory_utilisation:'
    expr: |
      1 -
      sum(node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
      /
      sum(node_memory_MemTotal_bytes{app="node-exporter"})

  - record: :node_memory_MemFreeCachedBuffers:sum
    expr: |
      sum(node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})

  - record: :node_memory_MemTotal:sum
    expr: |
      sum(node_memory_MemTotal_bytes{app="node-exporter"})

  - record: node:node_memory_bytes_available:sum
    expr: |
      sum by (node) (
        (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: node:node_memory_bytes_total:sum
    expr: |
      sum by (node) (
        node_memory_MemTotal_bytes{app="node-exporter"}
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: node:node_memory_utilisation:ratio
    expr: |
      (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
      /
      scalar(sum(node:node_memory_bytes_total:sum))

  - record: :node_memory_swap_io_bytes:sum_rate
    expr: |
      1e3 * sum(
        (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
        + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
      )

  - record: 'node:node_memory_utilisation:'
    expr: |
      1 -
      sum by (node) (
        (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
      /
      sum by (node) (
        node_memory_MemTotal_bytes{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: 'node:node_memory_utilisation_2:'
    expr: |
      1 - (node:node_memory_bytes_available:sum / node:node_memory_bytes_total:sum)

  - record: node:node_memory_swap_io_bytes:sum_rate
    expr: |
      1e3 * sum by (node) (
        (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
        + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: :node_disk_utilisation:avg_irate
    expr: |
      avg(irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]))

  - record: node:node_disk_utilisation:avg_irate
    expr: |
      avg by (node) (
        irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: :node_disk_saturation:avg_irate
    expr: |
      avg(irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]))

  - record: node:node_disk_saturation:avg_irate
    expr: |
      avg by (node) (
        irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: 'node:node_filesystem_usage:'
    expr: |
      max by (namespace, pod, device) (
        (node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} - node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
        /
        node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
      )

  - record: 'node:node_filesystem_avail:'
    expr: |
      max by (namespace, pod, device) (
        node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
      )

  - record: :node_net_utilisation:sum_irate
    expr: |
      sum(irate(node_network_receive_bytes_total{app="node-exporter",device="eth0"}[1m])) +
      sum(irate(node_network_transmit_bytes_total{app="node-exporter",device="eth0"}[1m]))

  - record: node:node_net_utilisation:sum_irate
    expr: |
      sum by (node) (
        (irate(node_network_receive_bytes_total{app="node-exporter",device="eth0"}[1m]) +
        irate(node_network_transmit_bytes_total{app="node-exporter",device="eth0"}[1m]))
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: :node_net_saturation:sum_irate
    expr: |
      sum(irate(node_network_receive_drop_total{app="node-exporter",device="eth0"}[1m])) +
      sum(irate(node_network_transmit_drop_total{app="node-exporter",device="eth0"}[1m]))

  - record: node:node_net_saturation:sum_irate
    expr: |
      sum by (node) (
        (irate(node_network_receive_drop_total{app="node-exporter",device="eth0"}[1m]) +
        irate(node_network_transmit_drop_total{app="node-exporter",device="eth0"}[1m]))
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: instance:node_num_cpu:sum
    expr: |
      count by (instance) (
        sum by (instance, cpu) (
          node_cpu_seconds_total{app="node-exporter"}
        )
      )

  - record: instance:node_cpu_utilisation:avg1m
    expr: |
      1 - avg by (instance) (
        rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m])
      )

  - record: 'instance:node_cpu_saturation_load1:'
    expr: |
      sum by (instance) (node_load1{app="node-exporter"})
      /
      instance:node_num_cpu:sum

  - record: instance:node_memory_bytes_total:sum
    expr: |
      sum by (instance) (
        node_memory_MemTotal_bytes{app="node-exporter"}
      )

  - record: instance:node_memory_utilisation:ratio
    expr: |
      1 - (
          node_memory_MemAvailable_bytes{app="node-exporter"}
        /
          node_memory_MemTotal_bytes{app="node-exporter"}
      )

  - record: instance:node_memory_swap_io_bytes:sum_rate
    expr: |
      1e3 * sum by (instance) (
        (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
          + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
      )

  - record: instance:node_disk_utilisation:sum_irate
    expr: |
      sum by (instance) (
        irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"(sd|xvd).+"}[1m])
      )

  - record: instance:node_disk_saturation:sum_irate
    expr: |
      sum by (instance) (
        irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"(sd|xvd).+"}[1m])
      )

  - record: instance:node_net_utilisation:sum_irate
    expr: |
      sum by (instance) (
        (irate(node_network_receive_bytes_total{app="node-exporter",device=~"eth[0-9]+"}[1m]) +
          irate(node_network_transmit_bytes_total{app="node-exporter",device=~"eth[0-9]+"}[1m]))
      )

  - record: instance:node_net_saturation:sum_irate
    expr: |
      sum by (instance) (
        (irate(node_network_receive_drop_total{app="node-exporter",device=~"eth[0-9]+"}[1m]) +
          irate(node_network_transmit_drop_total{app="node-exporter",device=~"eth[0-9]+"}[1m]))
      )

  ############################################################
  # alerts
  ############################################################

  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
        to run out of space within the next 24 hours.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemspacefillingup
    expr: |
      predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 24*60*60) < 0
      and
      node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.4
      and
      node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemSpaceFillingUp
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
        to run out of space within the next 4 hours.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemspacefillingup
    expr: |
      predict_linear(node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) < 0
      and
      node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} < 0.2
      and
      node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: critical

  - alert: NodeFilesystemOutOfSpace
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only
        {{ $value }}% available space left.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemoutofspace
    expr: |
      node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 5
      and
      node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemOutOfSpace
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only
        {{ $value }}% available space left.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemoutofspace
    expr: |
      node_filesystem_avail_bytes{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_size_bytes{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 3
      and
      node_filesystem_readonly_bytes{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: critical

  - alert: NodeFilesystemFilesFillingUp
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
        to run out of files within the next 24 hours.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemfilesfillingup
    expr: |
      predict_linear(node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"}[6h], 24*60*60) < 0
      and
      node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} < 0.4
      and
      node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemFilesFillingUp
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} is predicted
        to run out of files within the next 4 hours.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemfilesfillingup
    expr: |
      predict_linear(node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"}[6h], 4*60*60) < 0
      and
      node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} < 0.2
      and
      node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemOutOfFiles
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only
        {{ $value }}% available inodes left.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemoutoffiles
    expr: |
      node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 5
      and
      node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: warning

  - alert: NodeFilesystemOutOfSpace
    annotations:
      message:
        Filesystem on {{ $labels.device }} at {{ $labels.instance }} has only
        {{ $value }}% available space left.
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodefilesystemoutofspace
    expr: |
      node_filesystem_files_free{app="node-exporter",fstype=~"ext.|xfs"} / node_filesystem_files{app="node-exporter",fstype=~"ext.|xfs"} * 100 < 3
      and
      node_filesystem_readonly{app="node-exporter",fstype=~"ext.|xfs"} == 0
    for: 1h
    labels:
      severity: critical

  - alert: NodeNetworkReceiveErrs
    annotations:
      message:
        '{{ $labels.instance }} interface {{ $labels.device }} shows errors
        while receiving packets ({{ $value }} errors in two minutes).'
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodenetworkreceiveerrs
    expr: increase(node_network_receive_errs_total[2m]) > 10
    for: 1h
    labels:
      severity: critical

  - alert: NodeNetworkTransmitErrs
    annotations:
      message:
        '{{ $labels.instance }} interface {{ $labels.device }} shows errors
        while transmitting packets ({{ $value }} errors in two minutes).'
      runbook_url: https://docs.kubermatic.io/monitoring/runbook/#alert-nodenetworktransmiterrs
    expr: increase(node_network_transmit_errs_total[2m]) > 10
    for: 1h
    labels:
      severity: critical
