
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  creationTimestamp: null
  name: presets.kubermatic.k8c.io
spec:
  group: kubermatic.k8c.io
  names:
    kind: Preset
    listKind: PresetList
    plural: presets
    singular: preset
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Preset is the type representing a Preset
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Presets specifies default presets for supported providers
            properties:
              alibaba:
                properties:
                  accessKeyID:
                    type: string
                  accessKeySecret:
                    type: string
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                required:
                - accessKeyID
                - accessKeySecret
                type: object
              anexia:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  token:
                    description: Token is used to authenticate with the Anexia API.
                    type: string
                required:
                - token
                type: object
              aws:
                properties:
                  accessKeyID:
                    type: string
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  instanceProfileName:
                    type: string
                  roleARN:
                    type: string
                  routeTableID:
                    type: string
                  secretAccessKey:
                    type: string
                  securityGroupID:
                    type: string
                  vpcID:
                    type: string
                required:
                - accessKeyID
                - secretAccessKey
                type: object
              azure:
                properties:
                  clientID:
                    type: string
                  clientSecret:
                    type: string
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  loadBalancerSKU:
                    description: LoadBalancerSKU sets the LB type that will be used
                      for the Azure cluster, possible values are "basic" and "standard",
                      if empty, "basic" will be used
                    type: string
                  resourceGroup:
                    type: string
                  routeTable:
                    type: string
                  securityGroup:
                    type: string
                  subnet:
                    type: string
                  subscriptionID:
                    type: string
                  tenantID:
                    type: string
                  vnet:
                    type: string
                  vnetResourceGroup:
                    type: string
                required:
                - clientID
                - clientSecret
                - loadBalancerSKU
                - subscriptionID
                - tenantID
                type: object
              digitalocean:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  token:
                    description: Token is used to authenticate with the DigitalOcean
                      API.
                    type: string
                required:
                - token
                type: object
              enabled:
                type: boolean
              fake:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  token:
                    type: string
                required:
                - token
                type: object
              gcp:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  network:
                    type: string
                  serviceAccount:
                    type: string
                  subnetwork:
                    type: string
                required:
                - serviceAccount
                type: object
              hetzner:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  network:
                    description: Network is the pre-existing Hetzner network in which
                      the machines are running. While machines can be in multiple
                      networks, a single one must be chosen for the HCloud CCM to
                      work. If this is empty, the network configured on the datacenter
                      will be used.
                    type: string
                  token:
                    description: Token is used to authenticate with the Hetzner API.
                    type: string
                required:
                - token
                type: object
              kubevirt:
                properties:
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  kubeconfig:
                    type: string
                required:
                - kubeconfig
                type: object
              openstack:
                properties:
                  applicationCredentialID:
                    type: string
                  applicationCredentialSecret:
                    type: string
                  datacenter:
                    type: string
                  domain:
                    type: string
                  enabled:
                    type: boolean
                  floatingIPPool:
                    type: string
                  network:
                    type: string
                  password:
                    type: string
                  routerID:
                    type: string
                  securityGroups:
                    type: string
                  subnetID:
                    type: string
                  tenant:
                    type: string
                  tenantID:
                    type: string
                  useToken:
                    type: boolean
                  username:
                    type: string
                required:
                - domain
                - password
                - tenant
                - tenantID
                - username
                type: object
              packet:
                properties:
                  apiKey:
                    type: string
                  billingCycle:
                    type: string
                  datacenter:
                    type: string
                  enabled:
                    type: boolean
                  projectID:
                    type: string
                required:
                - apiKey
                - projectID
                type: object
              requiredEmailDomain:
                description: see RequiredEmails
                type: string
              requiredEmails:
                description: 'RequiredEmails: specify emails and domains RequiredEmailDomain
                  is appended to RequiredEmails for backward compatibility. e.g.:   RequiredEmailDomain:
                  "example.com"   RequiredEmails: ["foo.com", "foo.bar@test.com"]
                  Result:   *@example.com, *@foo.com and foo.bar@test.com can use
                  the Preset'
                items:
                  type: string
                type: array
              vsphere:
                properties:
                  datacenter:
                    type: string
                  datastore:
                    type: string
                  datastoreCluster:
                    type: string
                  enabled:
                    type: boolean
                  password:
                    type: string
                  resourcePool:
                    type: string
                  username:
                    type: string
                  vmNetName:
                    type: string
                required:
                - password
                - username
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
