cluster:
  name: log-data

node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

# bind to both interfaces so Kubernetes port-forwardings work as expected
network.bind_host: [_site_, _local_]

# publish only the external interface (pod IP) for communicating with other peers
network.publish_host: _site_

http:
  enabled: true
  compression: true

discovery:
  zen:
    minimum_master_nodes: ${MINIMUM_MASTER_NODES}
    ping:
      unicast:
        hosts:
          - es-master
          - es-data
