apiVersion: v1
name: elasticsearch
version: 1.0.2
appVersion: 6.7.1
description: Chart to deploy Elasticsearch master and data nodes.
keywords:
- kubermatic
- logging
- elasticsearch
- elastic
home: https://www.elastic.co/products/elasticsearch
sources:
- https://github.com/helm/charts/tree/master/stable/elasticsearch
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
