apiVersion: v2
version: v9.9.9-dev
appVersion: v1.10.0
description: 'Horizontally scalable, highly available, multi-tenant, long term Prometheus.'
home: https://cortexmetrics.io/
kubeVersion: ^1.19.0-0
name: cortex
sources:
  - https://github.com/cortexproject/cortex-helm-chart
dependencies:
- name: cortex
  repository: https://cortexproject.github.io/cortex-helm-chart
  version: 0.7.0
- alias: memcached
  condition: cortex.memcached.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.15.14
- alias: memcached-index-read
  condition: cortex.memcached-index-read.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.15.14
- alias: memcached-index-write
  condition: cortex.memcached-index-write.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.15.14
- alias: memcached-frontend
  condition: cortex.memcached-frontend.enabled
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  version: 5.15.14
- alias: memcached-blocks-index
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  tags:
  - blocks-storage-memcached
  version: 5.15.14
- alias: memcached-blocks
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  tags:
  - blocks-storage-memcached
  version: 5.15.14
- alias: memcached-blocks-metadata
  name: memcached
  repository: https://charts.bitnami.com/bitnami
  tags:
  - blocks-storage-memcached
  version: 5.15.14
