name: prometheus
version: 0.1.0
description: Prometheus
keywords:
  - k8s
  - kubermatic
home: http://www.kubermatic.io/
sources:
  - https://github.com/kubermatic/config
maintainers:
  - name: Sebastian Scheele
    email: sebastian@loodse.com
