{{ if not .Values.kubermatic.dynamicDatacenters }}
apiVersion: v1
kind: Secret
metadata:
  name: datacenters
type: Opaque
data:
  datacenters.yaml: {{ .Values.kubermatic.datacenters | quote }}
{{ end }}
