apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ .Values.kubermatic.domain }}
  backend:
    serviceName: kubermatic-ui
    servicePort: 80
  rules:
  - host: {{ .Values.kubermatic.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: kubermatic-api
          servicePort: 80
      - path: /
        backend:
          serviceName: kubermatic-ui
          servicePort: 80
