{{ if .Values.kubermatic.isMaster }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api
  annotations:
    kubernetes.io/ingress.class: {{ (default "nginx" .Values.kubermatic.ingressClass) }}
spec:
  tls:
  - secretName: kubermatic-tls
    hosts:
    - {{ .Values.kubermatic.domain }}
  backend:
    serviceName: kubermatic-dashboard
    servicePort: 80
  rules:
  - host: {{ .Values.kubermatic.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: kubermatic-api
          servicePort: 80
      - path: /
        backend:
          serviceName: kubermatic-dashboard
          servicePort: 80
{{ end }}
