{{ if (contains "VerticalPodAutoscaler=true" .Values.kubermatic.controller.featureGates) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-updater
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vpa-updater
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vpa-updater
      annotations:
        fluentbit.io/parser: glog
    spec:
      serviceAccountName: vpa-updater
      containers:
      - name: updater
        image: '{{ .Values.kubermatic.vpa.updater.image.repository }}:{{ .Values.kubermatic.vpa.updater.image.tag }}'
        command: ["/updater"]
        args:
        - "--address=:8943"
        # If a container was killed by a OOM trigger an update.
        - "--evict-after-oom-treshold=30m0s"
        - "--updater-interval=10m0s"
        - "--logtostderr"
        resources:
{{ toYaml .Values.kubermatic.vpa.updater.resources | indent 10 }}
        ports:
        - containerPort: 8080
      nodeSelector:
{{ toYaml .Values.kubermatic.vpa.updater.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.kubermatic.vpa.updater.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.kubermatic.vpa.updater.tolerations | indent 8 }}
{{ end }}
