apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v01.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "dev@loodse.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-acme-account-key
    # Enable the HTTP-01 challenge provider
    http01: {}
