{{ if .Values.ark.restic }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic
spec:
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      labels:
        name: restic
    spec:
      containers:
        - name: ark
          image: "{{ .Values.ark.image.repository }}:{{ .Values.ark.image.tag }}"
          imagePullPolicy: {{ .Values.ark.image.pullPolicy }}
          command:
            - /ark
          args:
            - restic
            - server
          {{- if .Values.ark.credentials.azure }}
          envFrom:
            - secretRef:
                name: azure-credentials
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HEPTIO_ARK_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ARK_SCRATCH_DIR
              value: /scratch
          {{- if .Values.ark.credentials.aws }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/aws/creds
          {{- end }}
          {{- if .Values.ark.credentials.gcp }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/gcp/creds
          {{- end }}
          volumeMounts:
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: scratch
              mountPath: /scratch
          {{- if .Values.ark.credentials.aws }}
            - name: aws-credentials
              mountPath: /credentials/aws
          {{- end }}
          {{- if .Values.ark.credentials.gcp }}
            - name: gcp-credentials
              mountPath: /credentials/gcp
          {{- end }}
      volumes:
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: scratch
          emptyDir: {}
      {{- if .Values.ark.credentials.aws }}
        - name: aws-credentials
          secret:
            secretName: aws-credentials
      {{- end }}
      {{- if .Values.ark.credentials.gcp }}
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
      {{- end }}
      serviceAccountName: ark-server
      securityContext:
        runAsUser: 0
{{ end }}
