apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ark-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ark-server
  template:
    metadata:
      labels:
        name: ark-server
      annotations:
        kubermatic/scrape: "true"
        kubermatic/scrape_port: "8085"
{{- with .Values.ark.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      restartPolicy: Always
      containers:
        - name: ark
          image: "{{ .Values.ark.image.repository }}:{{ .Values.ark.image.tag }}"
          imagePullPolicy: {{ .Values.ark.image.pullPolicy }}
          command:
            - /ark
          args:
            - server
            {{- range .Values.ark.serverFlags }}
            - '{{ . }}'
            {{- end }}
            {{- with .Values.ark.defaultBackupStorageLocation }}
            - '--default-backup-storage-location={{ . }}'
            {{- end }}
            {{- with .Values.ark.defaultVolumeSnapshotLocations }}
            - '--default-volume-snapshot-locations={{ . | join "," }}'
            {{- end }}
          {{- if .Values.ark.credentials.azure }}
          envFrom:
            - secretRef:
                name: azure-credentials
          {{- end }}
          env:
          {{- if .Values.ark.credentials.aws }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/aws/creds
          {{- end }}
          {{- if .Values.ark.credentials.gcp }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/gcp/creds
          {{- end }}
          volumeMounts:
            - name: plugins
              mountPath: /plugins
          {{- if .Values.ark.credentials.aws }}
            - name: aws-credentials
              mountPath: /credentials/aws
          {{- end }}
          {{- if .Values.ark.credentials.gcp }}
            - name: gcp-credentials
              mountPath: /credentials/gcp
          {{- end }}
          ports:
            - name: metrics
              containerPort: 8085
              protocol: TCP
      volumes:
        - name: plugins
          emptyDir: {}
      {{- if .Values.ark.credentials.aws }}
        - name: aws-credentials
          secret:
            secretName: aws-credentials
      {{- end }}
      {{- if .Values.ark.credentials.gcp }}
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
      {{- end }}
      serviceAccountName: ark-server
      nodeSelector:
{{ toYaml .Values.ark.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.ark.tolerations | indent 8 }}
