apiVersion: v1
name: grafana
version: 1.2.1
appVersion: 6.3.5
description: Grafana for Kubermatic
keywords:
- kubermatic
- monitoring
- grafana
home: https://grafana.com/
sources:
- https://github.com/helm/charts/tree/master/stable/grafana
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
