apiVersion: "nodeset.k8s.io/v1alpha1"
kind: NodeClass
metadata:
  name: {{ .Name }}
nodeController: kube-machine
config:
  dockerMachineFlags:
    openstack-auth-url: "{{ .Datacenter.Spec.Openstack.AuthURL }}"
    openstack-availability-zone: "{{ .Datacenter.Spec.Openstack.AvailabilityZone }}"
    openstack-flavor-name: "{{ .NodeSpec.Openstack.Flavor }}"
    openstack-domain-name: "{{ .Cluster.Spec.Cloud.Openstack.Domain }}"
    openstack-floatingip-pool: "{{ .Cluster.Spec.Cloud.Openstack.FloatingIPPool }}"
    openstack-image-name: "{{ .NodeSpec.Openstack.Image }}"
    openstack-password: "{{ .Cluster.Spec.Cloud.Openstack.Password }}"
    openstack-username: "{{ .Cluster.Spec.Cloud.Openstack.Username }}"
    openstack-tenant-name: "{{ .Cluster.Spec.Cloud.Openstack.Tenant }}"
    openstack-net-name: "{{ .Cluster.Spec.Cloud.Openstack.Network }}"
    openstack-sec-groups: "{{ .Cluster.Spec.Cloud.Openstack.SecurityGroups }}"
    openstack-ssh-user: "ubuntu"
  provider: openstack
  provisioning:
    users:
      - name: "apiserver"
        ssh_keys:
          {{range .Keys}}- {{.PublicKey}}
          {{end -}}
          - "{{ .Cluster.Status.ApiserverSSHKey.PublicKey | apiBytesToString }} apiserver@{{ .Cluster.Address.ExternalName }}"
        sudo: true
    commands:
      - "sudo systemctl start download-kubelet.service"
      - "sudo systemctl enable kubelet && sudo systemctl start kubelet"
    files:
      - path: "/etc/kubernetes/bootstrap.kubeconfig"
        permissions: "0640"
        owner: "root"
        content: |-
{{ .Kubeconfig | indent 10 }}
      - path: "/etc/systemd/system/download-kubelet.service"
        permissions: "0640"
        owner: "root"
        content: |-
          [Unit]
          Description=Download Kubelet and requirements
          After=network.target

          [Service]
          Type=oneshot
          ExecStartPre=/bin/mkdir -p /opt/bin /opt/cni/bin /etc/cni/net.d /var/run/kubernetes /var/lib/kubelet /etc/kubernetes/manifests /var/log/containers
          ExecStartPre=/bin/bash -c "/usr/bin/curl -L -o /tmp/cni-amd64.tgz https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz && tar -xvf /tmp/cni-amd64.tgz -C /opt/cni/bin/"
          ExecStartPre=/usr/bin/curl -L -o /opt/bin/socat https://s3-eu-west-1.amazonaws.com/kubermatic/coreos/socat
          ExecStartPre=/bin/chmod +x /opt/bin/socat
          ExecStart=/usr/bin/curl -L -o /opt/bin/kubelet https://storage.googleapis.com/kubelet/kubelet.v1.6.7
          ExecStartPost=/bin/chmod +x /opt/bin/kubelet
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target

      - path: "/etc/systemd/system/kubelet.service"
        permissions: "0640"
        owner: "root"
        content: |-
          [Unit]
          Description=Kubelet
          Requires=network.target download-kubelet.service
          After=network.target download-kubelet.service

          [Service]
          Restart=always
          RestartSec=10
          Environment="PATH=/sbin:/bin:/usr/sbin:/usr/bin:/opt/bin"
          ExecStart=/opt/bin/kubelet \
            --api-servers={{.Cluster.Address.URL}} \
            --container-runtime=docker \
            --allow-privileged=true \
            --pod-manifest-path=/etc/kubernetes/manifests \
            --cni-conf-dir=/etc/cni/net.d \
            --network-plugin=cni \
            --cluster-dns=10.10.10.10 \
            --cluster_domain=cluster.local \
            --kubeconfig=/etc/kubernetes/kubeconfig \
            --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
            --cert-dir=/etc/kubernetes/

          [Install]
          WantedBy=multi-user.target

      - path: "/etc/kubernetes/cloud-config"
        permissions: "0640"
        owner: "root"
        content: |-
          [Global]
          auth-url="{{ .Datacenter.Spec.Openstack.AuthURL }}"
          Username="{{ .Cluster.Spec.Cloud.Openstack.Username }}"
          password="{{ .Cluster.Spec.Cloud.Openstack.Password }}"
          domain-name="{{ .Cluster.Spec.Cloud.Openstack.Domain }}"
