---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
    kubermatic.k8c.io/location: master,seed
  name: mlaadminsettings.kubermatic.k8c.io
spec:
  group: kubermatic.k8c.io
  names:
    kind: MLAAdminSetting
    listKind: MLAAdminSettingList
    plural: mlaadminsettings
    singular: mlaadminsetting
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      name: v1
      schema:
        openAPIV3Schema:
          description: |-
            MLAAdminSetting is the object representing cluster-specific administrator settings
            for KKP user cluster MLA (monitoring, logging & alerting) stack.
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: |-
                Spec describes the cluster-specific administrator settings for KKP user cluster MLA
                (monitoring, logging & alerting) stack.
              properties:
                clusterName:
                  description: ClusterName is the name of the user cluster whose MLA settings are defined in this object.
                  type: string
                loggingRateLimits:
                  description: LoggingRateLimits contains rate-limiting configuration logging in the user cluster.
                  properties:
                    ingestionBurstSize:
                      description: IngestionBurstSize represents ingestion burst size in number of requests (nginx `burst`).
                      format: int32
                      type: integer
                    ingestionRate:
                      description: IngestionRate represents ingestion rate limit in requests per second (nginx `rate` in `r/s`).
                      format: int32
                      type: integer
                    queryBurstSize:
                      description: QueryBurstSize represents query burst size in number of requests (nginx `burst`).
                      format: int32
                      type: integer
                    queryRate:
                      description: QueryRate represents query request rate limit per second (nginx `rate` in `r/s`).
                      format: int32
                      type: integer
                  type: object
                monitoringRateLimits:
                  description: MonitoringRateLimits contains rate-limiting configuration for monitoring in the user cluster.
                  properties:
                    ingestionBurstSize:
                      description: IngestionBurstSize represents ingestion burst size in samples per second (Cortex `ingestion_burst_size`).
                      format: int32
                      type: integer
                    ingestionRate:
                      description: IngestionRate represents the ingestion rate limit in samples per second (Cortex `ingestion_rate`).
                      format: int32
                      type: integer
                    maxSamplesPerQuery:
                      description: MaxSamplesPerQuery represents maximum number of samples during a query (Cortex `max_samples_per_query`).
                      format: int32
                      type: integer
                    maxSeriesPerMetric:
                      description: MaxSeriesPerMetric represents maximum number of series per metric (Cortex `max_series_per_metric`).
                      format: int32
                      type: integer
                    maxSeriesPerQuery:
                      description: MaxSeriesPerQuery represents maximum number of timeseries during a query (Cortex `max_series_per_query`).
                      format: int32
                      type: integer
                    maxSeriesTotal:
                      description: MaxSeriesTotal represents maximum number of series per this user cluster (Cortex `max_series_per_user`).
                      format: int32
                      type: integer
                    queryBurstSize:
                      description: QueryBurstSize represents query burst size in number of requests (nginx `burst`).
                      format: int32
                      type: integer
                    queryRate:
                      description: QueryRate represents  query request rate limit per second (nginx `rate` in `r/s`).
                      format: int32
                      type: integer
                  type: object
              required:
                - clusterName
              type: object
          type: object
      served: true
      storage: true
      subresources: {}
