apiVersion: v1
name: cert-manager
version: 1.1.5
appVersion: v0.12.0-beta.1
description: A Helm chart for cert-manager
keywords:
- kubermatic
- cert-manager
- kube-lego
- letsencrypt
- tls
home: https://github.com/jetstack/cert-manager
sources:
- https://github.com/jetstack/cert-manager/tree/master/deploy/charts/cert-manager
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
