kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: {{ .Values.dex.ingress.scheme }}://{{ .Values.dex.ingress.host }}{{ .Values.dex.ingress.path }}
    oauth2:
      skipApprovalScreen: true
      responseTypes:
        - code
        - token
        - id_token
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    telemetry:
      http: 0.0.0.0:5558
    # this is a requirement for static passwords, so we just enable it by default
    enablePasswordDB: true
{{ if .Values.dex.expiry }}
    expiry:
{{ toYaml .Values.dex.expiry | indent 6 }}
{{- end }}
{{ if .Values.dex.grpc }}
    grpc:
{{ toYaml .Values.dex.grpc.api | indent 6 }}
{{- end }}
{{ if .Values.dex.connectors }}
    connectors:
{{ toYaml .Values.dex.connectors | indent 6 }}
{{- end }}
{{ if .Values.dex.clients }}
    staticClients:
{{ toYaml .Values.dex.clients | indent 6 }}
{{- end }}
{{ if or .Values.dex.staticPasswords .Values.dex.staticPasswordLogins }}
    staticPasswords:
{{- if .Values.dex.staticPasswords }}
{{ toYaml .Values.dex.staticPasswords | indent 6 }}
{{- end }}
{{- if .Values.dex.staticPasswordLogins }}
{{ toYaml .Values.dex.staticPasswordLogins | indent 6 }}
{{- end }}
{{- end }}
