{{- if ne .Values.dex.ingress.class "non-existent" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dex
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.dex.ingress.class }}"
spec:
  tls:
  - hosts:
    - {{ .Values.dex.ingress.host }}
  backend:
    serviceName: dex
    servicePort: 5556
  rules:
  - host: {{ .Values.dex.ingress.host }}
    http:
      paths:
      - path: {{ .Values.dex.ingress.path }}
        backend:
          serviceName: dex
          servicePort: 5556
{{ if .Values.dex.grpc }}{{ toYaml .Values.dex.grpc.ingress | trim | indent 6 }}
{{- end }}
{{- end }}
