apiVersion: v1
name: minio
version: 1.0.11
appVersion: RELEASE.2019-10-12T01-39-57Z
description: minio
keywords:
- kubermatic
- minio
- s3
home: https://www.minio.io/kubernetes.html
sources:
- https://www.minio.io/kubernetes.html
- https://github.com/helm/charts/tree/master/stable/minio
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
