apiVersion: v1
name: minio
version: 1.0.14
appVersion: RELEASE.2020-06-03T22-13-49Z
description: minio
keywords:
- kubermatic
- minio
- s3
home: https://www.minio.io/kubernetes.html
sources:
- https://www.minio.io/kubernetes.html
- https://github.com/helm/charts/tree/master/stable/minio
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
