minio:
  image:
    repository: "minio/minio"
    tag: "RELEASE.2018-06-09T03-43-35Z"
  storeSize: "100Gi"
  credentials:
    accessKey: "wtupllWfpMg414ZM5YkzZiUmgjh1vZdk"
    secretKey: "r89xkN9JvHJQppb5v7SEfkNkiC1vDcMySQFKxg6uDkE3gZfCeB7ZBfECyUOTywym"
