groups:
- name: node.rules
  rules:
  - record: ':kube_pod_info_node_count:'
    expr: |
      sum(min(kube_pod_info) by (node))

  - record: 'node_namespace_pod:kube_pod_info:'
    expr: |
      max(label_replace(kube_pod_info{job="kube-state-metrics"}, "pod", "$1", "pod", "(.*)")) by (node, namespace, pod)

  - record: node:node_num_cpu:sum
    expr: |
      count by (node) (sum by (node, cpu) (
        node_cpu_seconds_total{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      ))

  - record: :node_cpu_utilisation:avg1m
    expr: |
      1 - avg(rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m]))

  - record: node:node_cpu_utilisation:avg1m
    expr: |
      1 - avg by (node) (
        rate(node_cpu_seconds_total{app="node-exporter",mode="idle"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:)

  - record: ':node_cpu_saturation_load1:'
    expr: |
      sum(node_load1{app="node-exporter"})
      /
      sum(node:node_num_cpu:sum)

  - record: 'node:node_cpu_saturation_load1:'
    expr: |
      sum by (node) (
        node_load1{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
      /
      node:node_num_cpu:sum

  - record: ':node_memory_utilisation:'
    expr: |
      1 -
      sum(node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
      /
      sum(node_memory_MemTotal_bytes{app="node-exporter"})

  - record: :node_memory_MemFreeCachedBuffers:sum
    expr: |
      sum(node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})

  - record: :node_memory_MemTotal:sum
    expr: |
      sum(node_memory_MemTotal_bytes{app="node-exporter"})

  - record: node:node_memory_bytes_available:sum
    expr: |
      sum by (node) (
        (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: node:node_memory_bytes_total:sum
    expr: |
      sum by (node) (
        node_memory_MemTotal_bytes{app="node-exporter"}
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: node:node_memory_utilisation:ratio
    expr: |
      (node:node_memory_bytes_total:sum - node:node_memory_bytes_available:sum)
      /
      scalar(sum(node:node_memory_bytes_total:sum))

  - record: :node_memory_swap_io_bytes:sum_rate
    expr: |
      1e3 * sum(
        (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
        + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
      )

  - record: 'node:node_memory_utilisation:'
    expr: |
      1 -
      sum by (node) (
        (node_memory_MemFree_bytes{app="node-exporter"} + node_memory_Cached_bytes{app="node-exporter"} + node_memory_Buffers_bytes{app="node-exporter"})
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
      /
      sum by (node) (
        node_memory_MemTotal_bytes{app="node-exporter"}
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: 'node:node_memory_utilisation_2:'
    expr: |
      1 - (node:node_memory_bytes_available:sum / node:node_memory_bytes_total:sum)

  - record: node:node_memory_swap_io_bytes:sum_rate
    expr: |
      1e3 * sum by (node) (
        (rate(node_vmstat_pgpgin{app="node-exporter"}[1m])
        + rate(node_vmstat_pgpgout{app="node-exporter"}[1m]))
        * on (namespace, pod) group_left(node)
          node_namespace_pod:kube_pod_info:
      )

  - record: :node_disk_utilisation:avg_irate
    expr: |
      avg(irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]))

  - record: node:node_disk_utilisation:avg_irate
    expr: |
      avg by (node) (
        irate(node_disk_io_time_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: :node_disk_saturation:avg_irate
    expr: |
      avg(irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m]))

  - record: node:node_disk_saturation:avg_irate
    expr: |
      avg by (node) (
        irate(node_disk_io_time_weighted_seconds_total{app="node-exporter",device=~"(sd|xvd|nvme).+"}[1m])
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: 'node:node_filesystem_usage:'
    expr: |
      max by (namespace, pod, device) (
        (node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} - node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"})
        /
        node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
      )

  - record: 'node:node_filesystem_avail:'
    expr: |
      max by (namespace, pod, device) (
        node_filesystem_avail_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"} / node_filesystem_size_bytes{fstype=~"ext[234]|btrfs|xfs|zfs"}
      )

  - record: :node_net_utilisation:sum_irate
    expr: |
      sum(irate(node_network_receive_bytes_total{app="node-exporter",device="eth0"}[1m])) +
      sum(irate(node_network_transmit_bytes_total{app="node-exporter",device="eth0"}[1m]))

  - record: node:node_net_utilisation:sum_irate
    expr: |
      sum by (node) (
        (irate(node_network_receive_bytes_total{app="node-exporter",device="eth0"}[1m]) +
        irate(node_network_transmit_bytes_total{app="node-exporter",device="eth0"}[1m]))
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )

  - record: :node_net_saturation:sum_irate
    expr: |
      sum(irate(node_network_receive_drop_total{app="node-exporter",device="eth0"}[1m])) +
      sum(irate(node_network_transmit_drop_total{app="node-exporter",device="eth0"}[1m]))

  - record: node:node_net_saturation:sum_irate
    expr: |
      sum by (node) (
        (irate(node_network_receive_drop_total{app="node-exporter",device="eth0"}[1m]) +
        irate(node_network_transmit_drop_total{app="node-exporter",device="eth0"}[1m]))
      * on (namespace, pod) group_left(node)
        node_namespace_pod:kube_pod_info:
      )
