apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  ports:
    - port: 9300
      name: transport
    - port: 9200
      name: http
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
