apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9114"
        kubermatic.io/chart: elasticsearch
    spec:
      containers:
      - name: exporter
        image: "{{ .Values.logging.elasticsearch.exporter.image.repository }}:{{ .Values.logging.elasticsearch.exporter.image.tag }}"
        imagePullPolicy: {{ .Values.logging.elasticsearch.exporter.image.pullPolicy }}
        command:
        - elasticsearch_exporter
        args:
        - '--es.uri=http://es-data:9200'
        {{- if .Values.logging.elasticsearch.exporter.all }}
        - '--es.all'
        {{- end }}
        {{- if .Values.logging.elasticsearch.exporter.indices }}
        - '--es.indices'
        {{- end }}
        {{- if .Values.logging.elasticsearch.exporter.indices_settings }}
        - '--es.indices_settings'
        {{- end }}
        {{- if .Values.logging.elasticsearch.exporter.shards }}
        - '--es.shards'
        {{- end }}
        resources:
{{ toYaml .Values.logging.elasticsearch.exporter.resources | indent 10 }}
        ports:
        - containerPort: 9114
          name: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector:
{{ toYaml .Values.logging.elasticsearch.exporter.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.logging.elasticsearch.exporter.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.logging.elasticsearch.exporter.tolerations | indent 8 }}
