karma:
  kubermaticNamespace: kubermatic
  config: |
    log:
      config: false
      level: warning
      format: json

    filters:
      default:
      # only show active alerts
      - "@state=active"

    receivers:
      strip:
      # prevent alerts from showing up multiple times
      - '@critical-alerts'

    alertmanager:
      interval: 60s
      servers:

  images:
    karma:
      repository: docker.io/lmierzwa/karma
      tag: v0.55
      pullPolicy: IfNotPresent
    initContainer:
      repository: quay.io/kubermatic/util
      tag: 1.3.2
      pullPolicy: IfNotPresent
  resources:
    karma:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 48Mi
  nodeSelector: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: '{{ template "name" . }}'
          topologyKey: kubernetes.io/hostname
        weight: 100
  tolerations: []
