apiVersion: v1
name: s3-exporter
version: 1.1.0
appVersion: v0.4
keywords:
- kubermatic
- prometheus
- s3
- minio
home: https://www.kubermatic.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
