apiVersion: v2
name: consul
version: v9.9.9-dev
appVersion: 1.10.3
kubeVersion: ">=1.17.0-0"
description: Official HashiCorp Consul Chart
home: https://www.consul.io
icon: https://raw.githubusercontent.com/hashicorp/consul-k8s/main/assets/icon.png
sources:
  - https://github.com/hashicorp/consul
  - https://github.com/hashicorp/consul-k8s
dependencies:
  - name: consul
    repository: https://helm.releases.hashicorp.com
    version: 0.36.0
