apiVersion: v1
name: velero
version: 1.2.1
appVersion: v1.2.0
description: A Helm chart for Heptio Velero
keywords:
- kubermatic
- backup
- velero
home: https://velero.io/
sources:
- https://github.com/vmware-tanzu/velero
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
