apiVersion: v1
name: velero
version: 1.1.1
appVersion: v1.0.0
description: A Helm chart for Heptio Velero
keywords:
- kubermatic
- backup
- velero
home: https://heptio.com/community/velero/
sources:
- https://github.com/heptio/velero/tree/master/examples
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
