# Copyright 2021 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{ if .Cluster.MLA.MonitoringEnabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-custom-scrape-configs-node-exporter
  namespace: mla-system
data:
  custom-scrape-configs.yaml: |+
    - job_name: node-exporter
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_app_kubernetes_io_name]
          regex: kube-system;node-exporter
          action: keep
        - source_labels: [__meta_kubernetes_pod_node_name]
          action: replace
          regex: (.+)
          replacement: $1
          target_label: node_name

{{ end }}
