name: alertmanager
version: 0.1.0
description: Alertmanager for Kubermatic
keywords:
  - k8s
  - kubermatic
  - prometheus
  - alertmanager
home: http://www.kubermatic.io/
sources:
  - https://github.com/kubermatic/kubermatic/config
maintainers:
  - name: Sebastian Scheele
    email: sebastian@loodse.com
