apiVersion: v1
name: alertmanager
version: 2.0.2
appVersion: v0.18.0
description: Alertmanager for Kubermatic
keywords:
- kubermatic
- monitoring
- prometheus
- alertmanager
home: https://prometheus.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
