apiVersion: v1
name: fluentbit
version: 1.5.1
appVersion: 1.2.2
description: Helm chart to install fluent-bit as a log shipper DaemonSet.
keywords:
- kubermatic
- logging
- fluentbit
home: http://fluentbit.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
