apiVersion: v1
name: kubermatic
version: 1.0.44
appVersion: '__KUBERMATIC_TAG__'
description: Kubermatic chart for master and/or seed clusters.
keywords:
- kubermatic
home: https://www.kubermatic.io/
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
