apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: settings.kubermatic.k8s.io
spec:
  group: kubermatic.k8s.io
  names:
    kind: KubermaticSettings
    listKind: KubermaticSettingsList
    plural: kubermaticsettings
    singular: kubermaticsettings
  scope: Namespaced
  version: v1alpha1