apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-kubermatic
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # type of authentication
    ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    ingress.kubernetes.io/auth-secret: prometheus-kubermatic-auth
    # message to display with an appropiate context why the authentication is required
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    # always load balance to the same prometheus based on a IP, this is needed for Prometheus Federation.
    ingress.kubernetes.io/upstream-hash-by: "ip_hash"
spec:
  tls:
  - hosts:
    - {{ .Values.prometheus.host | trim }}
  backend:
    serviceName: prometheus-kubermatic
    servicePort: 9090
  rules:
  - host: {{ .Values.prometheus.host | trim }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-kubermatic
          servicePort: web
