apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kubermatic
  labels:
    app: prometheus
spec:
  replicas: 2
  version: {{ .Values.prometheus.version }}
  retention: 360h
  serviceAccountName: prometheus-kubermatic
  externalUrl: https://{{ .Values.prometheus.host | trim }}
  serviceMonitorSelector:
    matchLabels:
      team: kubermatic
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name: alertmanager-kubermatic
      port: web
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: kubermatic
  resources:
    requests:
      memory: 1G
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: kubermatic-fast
