apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clusters
  labels:
    team: kubermatic
spec:
  selector:
    matchLabels:
      cluster: user
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    interval: 30s
    path: /federate
    honorLabels: true
    params:
      'match[]':
        - '{__name__="up"}'
        - '{__name__=~"etcd.*"}'
        - '{__name__=~"machine_controller.*"}'
