# Copyright 2021 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: batch/v1
kind: CronJob
metadata:
  name: minio-lifecycle-mgr
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.lifecycleMgr.imagePullSecrets }}
          imagePullSecrets: {{- toYaml .Values.lifecycleMgr.imagePullSecrets | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          containers:
            - name: minio
              image: '{{ .Values.lifecycleMgr.image.repository }}:{{ .Values.lifecycleMgr.image.tag }}'
              imagePullPolicy: '{{ .Values.lifecycleMgr.image.pullPolicy }}'
              command:
                - /bin/sh
                - -ec
                - /scripts/ensure-lifecycle.sh
              envFrom:
                - secretRef:
                    name: {{ .Values.lifecycleMgr.minio.secretName }}
              volumeMounts:
                - mountPath: /scripts
                  name: scripts
          volumes:
            - name: scripts
              configMap:
                name: minio-lifecycle-mgr-scripts
                defaultMode: 0777
{{- with .Values.lifecycleMgr.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.lifecycleMgr.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.lifecycleMgr.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
{{- end }}
