# We only update the etcd-operator version explicitly, not the whole template
versions:
- name: 1.6.7
  id: 1.6.7
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  nodeControllerDeploymentYaml: node-controller-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  values:
    k8s-version: v1.6.7
    etcd-operator-version: v0.2.4fix
    etcd-cluster-version: 3.1.5
    kube-machine-version: v0.1.3
    addon-manager-version: v1.6.2
- name: 1.6.8
  id: 1.6.8
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  nodeControllerDeploymentYaml: node-controller-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  values:
    k8s-version: v1.6.8
    etcd-operator-version: v0.2.4fix
    etcd-cluster-version: 3.1.5
    kube-machine-version: v0.1.3
    addon-manager-version: v1.6.2
- name: 1.6.9
  id: 1.6.9
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  nodeControllerDeploymentYaml: node-controller-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  values:
    k8s-version: v1.6.9
    etcd-operator-version: v0.2.4fix
    etcd-cluster-version: 3.1.5
    kube-machine-version: v0.1.3
    addon-manager-version: v1.6.2
- name: 1.6.10
  id: 1.6.10
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  nodeControllerDeploymentYaml: node-controller-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  values:
    k8s-version: v1.6.10
    etcd-operator-version: v0.2.4fix
    etcd-cluster-version: 3.1.5
    kube-machine-version: v0.1.3
    addon-manager-version: v1.6.2
