# We support 1.9,1.10,1.11 & kubernetes is able to handle the whole matrix of those versions
allowed-node-versions: &node-versions
- "1.10.*"
- "1.11.*"
- "1.12.*"

versions:
# Kubernetes 1.10
- version: "1.10.11"
  default: false
  allowedNodeVersions: *node-versions
# Kubernetes 1.11
- version: "1.11.5"
  default: true
  allowedNodeVersions: *node-versions
# Kubernetes 1.12
- version: "1.12.3"
  default: false
  allowedNodeVersions: *node-versions
