# We support 1.10,1.11,1.12 & kubernetes is able to handle the whole matrix of those versions
allowed-node-versions: &node-versions
- "1.10.*"
- "1.11.*"
- "1.12.*"

versions:
# Kubernetes 1.10
- version: "1.10.1"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.2"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.3"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.4"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.5"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.6"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.7"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.8"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.10.11"
  default: false
  allowedNodeVersions: *node-versions
# Kubernetes 1.11
- version: "1.11.0"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.11.1"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.11.2"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.11.3"
  default: true
  allowedNodeVersions: *node-versions
- version: "1.11.4"
  default: true
  allowedNodeVersions: *node-versions
- version: "1.11.5"
  default: true
  allowedNodeVersions: *node-versions
# Kubernetes 1.12
- version: "1.12.0"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.12.1"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.12.2"
  default: false
  allowedNodeVersions: *node-versions
- version: "1.12.3"
  default: false
  allowedNodeVersions: *node-versions
