versions:
# Kubernetes 1.15
- version: "v1.15.5"
  default: false
- version: "v1.15.6"
  default: false
- version: "v1.15.7"
  default: false
- version: "v1.15.9"
  default: false
- version: "v1.15.10"
  default: true
# Kubernetes 1.16
- version: "v1.16.13"
  default: false
# OpenShift 4.1.9
- version: "v4.1.9"
  default: false
  type: "openshift"
# OpenShift 4.1.18
- version: "v4.1.18"
  default: true
  type: "openshift"
