versions:
# Kubernetes 1.13
- version: "1.13.10"
  default: false
# Kubernetes 1.14
- version: "v1.14.6"
  default: true
# Kubernetes 1.15
- version: "v1.15.3"
  default: false
# OpenShift 4.1.9
- version: "v4.1.9"
  default: true
  type: "openshift"
