# We only update the etcd-operator version explicitly, not the whole template
versions:
- name: 1.8.4
  id: 1.8.4
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.8.4
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.8.5
  id: 1.8.5
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.8.5
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.8.6
  id: 1.8.6
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.8.6
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.8.7
  id: 1.8.7
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.8.7
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.0
  id: 1.9.0
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.0
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.1
  id: 1.9.1
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.1
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.2
  id: 1.9.2
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.2
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.3
  id: 1.9.3
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.3
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.4
  id: 1.9.4
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.4
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.5
  id: 1.9.5
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.5
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.9.6
  id: 1.9.6
  default: true
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.9.6
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.10.1
  id: 1.10.1
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.10.1
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
- name: 1.10.2
  id: 1.10.2
  default: false
  allowedNodeVersions: [1.4.0]
  etcdOperatorDeploymentYaml: etcd-operator-dep.yaml
  etcdClusterYaml: etcd-cluster.yaml
  apiserverDeploymentYaml: apiserver-dep.yaml
  controllerDeploymentYaml: controller-manager-dep.yaml
  schedulerDeploymentYaml: scheduler-dep.yaml
  addonManagerDeploymentYaml: addon-manager-dep.yaml
  machineControllerDeploymentYaml: machine-controller-dep.yaml
  kubeStateMetricsDeploymentYaml: kube-state-metrics-dep.yaml
  openVPNServerDeploymentYaml: openvpn-server-dep.yaml
  values:
    k8s-version: v1.10.2
    etcd-operator-version: v0.6.0
    etcd-cluster-version: 3.2.7
    kube-machine-version: v0.2.3
    addon-manager-version: v1.9.5
    pod-network-bridge: v0.4
    machine-controller-version: v0.6.2
    kube-state-metrics-version: latest
