apiVersion: v1
name: nginx-ingress-controller
version: 1.0.2
appVersion: 0.25.1
description: nginx-ingress-controller
keywords:
- kubermatic
- nginx-ingress-controller
- nginx
home: https://github.com/kubernetes/ingress/
sources:
- https://github.com/kubernetes/ingress/tree/master/controllers/nginx
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
