##### Kubermatic ingress
nginx:
  hostNetwork: false
  asDaemonSet: false
  replicas: 3
  ignoreMasterTaint: false
  prometheus:
    port: "10254"
    scrape: "true"
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: 0.14.0
  defaultBackend:
    image:
      repository: gcr.io/google_containers/defaultbackend
      tag: 1.4
  config: {}
#    load-balance: "least_conn"