name: k8sniff
version: 0.1.0
description: Kubermatic k8sniff
keywords:
  - k8s
  - kubermatic
home: http://www.kubermatic.io/
sources:
  - https://github.com/kubermatic/config
maintainers:
  - name: Sebastian Scheele
    email: sebastian@loodse.com
