apiVersion: v1
name: kube-state-metrics
version: 1.0.7
appVersion: v1.9.4
description: Kube-State-Metrics for Kubermatic
keywords:
- kubermatic
- monitoring
- prometheus
- kube-state-metrics
home: https://github.com/kubernetes/kube-state-metrics
sources:
- https://github.com/kubermatic/kubermatic
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
