kubeStateMetrics:
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.6.0
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

  resizer:
    image:
      repository: gcr.io/google_containers/addon-resizer
      tag: '1.8.4'
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 48Mi

  nodeSelector: {}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: kube-state-metrics
          topologyKey: kubernetes.io/hostname
        weight: 100
  tolerations: []
