apiVersion: v1
name: prometheus
version: 1.1.2
appVersion: v2.8.1
description: Prometheus for Kubermatic
keywords:
- kubermatic
- monitoring
- prometheus
home: https://prometheus.io/
sources:
- https://github.com/helm/charts/tree/master/stable/prometheus
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
