apiVersion: v1
name: prometheus
version: 2.2.11
appVersion: v2.14.0
description: Prometheus Monitoring for Kubernetes
keywords:
- kubermatic
- monitoring
- prometheus
- thanos
home: https://prometheus.io/
sources:
- https://github.com/helm/charts/tree/master/stable/prometheus
- https://github.com/improbable-eng/thanos/tree/master/tutorials/kubernetes-demo/manifests
maintainers:
- name: Loodse GmbH
  email: support@loodse.com
